// <auto-generated />
using System;
using Fakultet.Servisi.Bazni;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fakultet.Servisi.Migrations
{
    [DbContext(typeof(FakultetAppDbContext))]
    [Migration("20260720103539_DodanAktivan")]
    partial class DodanAktivan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fakultet.Core.Modeli.AsistentPredmet", b =>
                {
                    b.Property<int>("AsistentId")
                        .HasColumnType("int");

                    b.Property<int>("PredmetId")
                        .HasColumnType("int");

                    b.HasKey("AsistentId", "PredmetId");

                    b.HasIndex("PredmetId");

                    b.ToTable("AsistentiPredmeti");
                });

            modelBuilder.Entity("Fakultet.Core.Modeli.Drzava", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oznaka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Regija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Drzave");
                });

            modelBuilder.Entity("Fakultet.Core.Modeli.Forum.ChatPoruka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PosiljalacId")
                        .HasColumnType("int");

                    b.Property<int>("PrimalacId")
                        .HasColumnType("int");

                    b.Property<bool>("Procitano")
                        .HasColumnType("bit");

                    b.Property<string>("Sadrzaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VrijemeSlanja")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PosiljalacId");

                    b.HasIndex("PrimalacId");

                    b.ToTable("ChatPoruke");
                });

            modelBuilder.Entity("Fakultet.Core.Modeli.Forum.Materijal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumPostavljanja")
                        .HasColumnType("datetime2");

                    b.Property<string>("LinkDoVidea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OsobaId")
                        .HasColumnType("int");

                    b.Property<int>("PredmetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OsobaId");

                    b.HasIndex("PredmetId");

                    b.ToTable("Materijali");
                });

            modelBuilder.Entity("Fakultet.Core.Modeli.Forum.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumObjave")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OsobaId")
                        .HasColumnType("int");

                    b.Property<int?>("PredmetId")
                        .HasColumnType("int");

                    b.Property<string>("Sadrzaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OsobaId");

                    b.HasIndex("PredmetId");

                    b.ToTable("Postovi");
                });

            modelBuilder.Entity("Fakultet.Core.Modeli.Forum.ZahtjevZaPotvrdu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumPodnosenja")
                        .HasColumnType("datetime2");

                    b.Property<int>("StanjePotvrde")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SvrhaPotvrde")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("ZahtjeviZaPotvrde");
                });

            modelBuilder.Entity("Fakultet.Core.Modeli.GodinaStudija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudijId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudijId");

                    b.ToTable("GodineStudija");
                });

            modelBuilder.Entity("Fakultet.Core.Modeli.Grad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DrzavaId")
                        .HasColumnType("int");

                    b.Property<string>("Kanton")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DrzavaId");

                    b.ToTable("Gradovi");
                });

            modelBuilder.Entity("Fakultet.Core.Modeli.Ispit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrojZadataka")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumOdrzavanja")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxBrojBodova")
                        .HasColumnType("int");

                    b.Property<int>("PredmetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PredmetId");

                    b.ToTable("Ispiti");
                });

            modelBuilder.Entity("Fakultet.Core.Modeli.Osoba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivan")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GradId")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpolId")
                        .HasColumnType("int");

                    b.Property<int>("Uloge")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GradId");

                    b.HasIndex("SpolId");

                    b.ToTable("Osobe");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Fakultet.Core.Modeli.Predmet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ECTS")
                        .HasColumnType("int");

                    b.Property<int>("GodinaStudijaId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfesorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GodinaStudijaId");

                    b.HasIndex("ProfesorId");

                    b.ToTable("Predmeti");
                });

            modelBuilder.Entity("Fakultet.Core.Modeli.Spol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oznaka")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.ToTable("Spolovi");
                });

            modelBuilder.Entity("Fakultet.Core.Modeli.StudentIspit", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("IspitId")
                        .HasColumnType("int");

                    b.Property<int>("BrojIzlazaka")
                        .HasColumnType("int");

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DatumPrijave")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Dodatni")
                        .HasColumnType("bit");

                    b.Property<bool>("Komisijski")
                        .HasColumnType("bit");

                    b.Property<int?>("Ocjena")
                        .HasColumnType("int");

                    b.Property<bool>("Polozio")
                        .HasColumnType("bit");

                    b.HasKey("StudentId", "IspitId");

                    b.HasIndex("IspitId");

                    b.ToTable("StudentiIspiti");
                });

            modelBuilder.Entity("Fakultet.Core.Modeli.StudentPredmet", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("PredmetId")
                        .HasColumnType("int");

                    b.Property<int>("BrojBodova")
                        .HasColumnType("int");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Ocjena")
                        .HasColumnType("int");

                    b.Property<bool>("Polozio")
                        .HasColumnType("bit");

                    b.HasKey("StudentId", "PredmetId");

                    b.HasIndex("PredmetId");

                    b.ToTable("StudentiPredmeti");
                });

            modelBuilder.Entity("Fakultet.Core.Modeli.Studij", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Smjer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zvanje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Studiji");
                });

            modelBuilder.Entity("Fakultet.Core.Modeli.Asistent", b =>
                {
                    b.HasBaseType("Fakultet.Core.Modeli.Osoba");

                    b.Property<decimal>("Plata")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("Asistenti", (string)null);
                });

            modelBuilder.Entity("Fakultet.Core.Modeli.Profesor", b =>
                {
                    b.HasBaseType("Fakultet.Core.Modeli.Osoba");

                    b.Property<float>("Ocjena")
                        .HasColumnType("real");

                    b.Property<decimal>("Plata")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Zvanje")
                        .HasColumnType("int");

                    b.ToTable("Profesori", (string)null);
                });

            modelBuilder.Entity("Fakultet.Core.Modeli.Student", b =>
                {
                    b.HasBaseType("Fakultet.Core.Modeli.Osoba");

                    b.Property<DateTime>("DatumUpisa")
                        .HasColumnType("datetime2");

                    b.Property<int>("GodinaStudijaId")
                        .HasColumnType("int");

                    b.Property<string>("Indeks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("ZavrsioFakultet")
                        .HasColumnType("bit");

                    b.HasIndex("GodinaStudijaId");

                    b.ToTable("Studenti", (string)null);
                });

            modelBuilder.Entity("Fakultet.Core.Modeli.AsistentPredmet", b =>
                {
                    b.HasOne("Fakultet.Core.Modeli.Asistent", "Asistent")
                        .WithMany()
                        .HasForeignKey("AsistentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fakultet.Core.Modeli.Predmet", "Predmet")
                        .WithMany()
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asistent");

                    b.Navigation("Predmet");
                });

            modelBuilder.Entity("Fakultet.Core.Modeli.Forum.ChatPoruka", b =>
                {
                    b.HasOne("Fakultet.Core.Modeli.Osoba", "Posiljalac")
                        .WithMany()
                        .HasForeignKey("PosiljalacId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fakultet.Core.Modeli.Osoba", "Primalac")
                        .WithMany()
                        .HasForeignKey("PrimalacId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Posiljalac");

                    b.Navigation("Primalac");
                });

            modelBuilder.Entity("Fakultet.Core.Modeli.Forum.Materijal", b =>
                {
                    b.HasOne("Fakultet.Core.Modeli.Osoba", "Osoba")
                        .WithMany()
                        .HasForeignKey("OsobaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fakultet.Core.Modeli.Predmet", "Predmet")
                        .WithMany()
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Osoba");

                    b.Navigation("Predmet");
                });

            modelBuilder.Entity("Fakultet.Core.Modeli.Forum.Post", b =>
                {
                    b.HasOne("Fakultet.Core.Modeli.Osoba", "Osoba")
                        .WithMany()
                        .HasForeignKey("OsobaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fakultet.Core.Modeli.Predmet", "Predmet")
                        .WithMany()
                        .HasForeignKey("PredmetId");

                    b.Navigation("Osoba");

                    b.Navigation("Predmet");
                });

            modelBuilder.Entity("Fakultet.Core.Modeli.Forum.ZahtjevZaPotvrdu", b =>
                {
                    b.HasOne("Fakultet.Core.Modeli.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Fakultet.Core.Modeli.GodinaStudija", b =>
                {
                    b.HasOne("Fakultet.Core.Modeli.Studij", "Studij")
                        .WithMany()
                        .HasForeignKey("StudijId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Studij");
                });

            modelBuilder.Entity("Fakultet.Core.Modeli.Grad", b =>
                {
                    b.HasOne("Fakultet.Core.Modeli.Drzava", "Drzava")
                        .WithMany()
                        .HasForeignKey("DrzavaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drzava");
                });

            modelBuilder.Entity("Fakultet.Core.Modeli.Ispit", b =>
                {
                    b.HasOne("Fakultet.Core.Modeli.Predmet", "Predmet")
                        .WithMany()
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Predmet");
                });

            modelBuilder.Entity("Fakultet.Core.Modeli.Osoba", b =>
                {
                    b.HasOne("Fakultet.Core.Modeli.Grad", "Grad")
                        .WithMany()
                        .HasForeignKey("GradId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fakultet.Core.Modeli.Spol", "Spol")
                        .WithMany()
                        .HasForeignKey("SpolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grad");

                    b.Navigation("Spol");
                });

            modelBuilder.Entity("Fakultet.Core.Modeli.Predmet", b =>
                {
                    b.HasOne("Fakultet.Core.Modeli.GodinaStudija", "GodinaStudija")
                        .WithMany()
                        .HasForeignKey("GodinaStudijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fakultet.Core.Modeli.Profesor", "Profesor")
                        .WithMany()
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GodinaStudija");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("Fakultet.Core.Modeli.StudentIspit", b =>
                {
                    b.HasOne("Fakultet.Core.Modeli.Ispit", "Ispit")
                        .WithMany()
                        .HasForeignKey("IspitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fakultet.Core.Modeli.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ispit");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Fakultet.Core.Modeli.StudentPredmet", b =>
                {
                    b.HasOne("Fakultet.Core.Modeli.Predmet", "Predmet")
                        .WithMany()
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fakultet.Core.Modeli.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Predmet");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Fakultet.Core.Modeli.Asistent", b =>
                {
                    b.HasOne("Fakultet.Core.Modeli.Osoba", null)
                        .WithOne()
                        .HasForeignKey("Fakultet.Core.Modeli.Asistent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fakultet.Core.Modeli.Profesor", b =>
                {
                    b.HasOne("Fakultet.Core.Modeli.Osoba", null)
                        .WithOne()
                        .HasForeignKey("Fakultet.Core.Modeli.Profesor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fakultet.Core.Modeli.Student", b =>
                {
                    b.HasOne("Fakultet.Core.Modeli.GodinaStudija", "GodinaStudija")
                        .WithMany()
                        .HasForeignKey("GodinaStudijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fakultet.Core.Modeli.Osoba", null)
                        .WithOne()
                        .HasForeignKey("Fakultet.Core.Modeli.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GodinaStudija");
                });
#pragma warning restore 612, 618
        }
    }
}
